const diseaseSpecialtyMap = {
    'Fungal infection': 'dermatologist',
    'Allergy': 'allergist',
    'GERD': 'gastroenterologist',
    'Chronic cholestasis': 'hepatologist',
    'Drug Reaction': 'allergist',
    'Peptic ulcer diseae': 'gastroenterologist',
    'AIDS': 'infectious_disease',
    'Diabetes ': 'endocrinologist',
    'Gastroenteritis': 'gastroenterologist',
    'Bronchial Asthma': 'pulmonologist',
    'Hypertension ': 'cardiologist',
    'Migraine': 'neurologist',
    'Cervical spondylosis': 'orthopedic',
    'Paralysis (brain hemorrhage)': 'neurologist',
    'Jaundice': 'hepatologist',
    'Malaria': 'infectious_disease',
    'Chicken pox': 'pediatrician',
    'Dengue': 'infectious_disease',
    'Typhoid': 'infectious_disease',
    'hepatitis A': 'hepatologist',
    'Hepatitis B': 'hepatologist',
    'Hepatitis C': 'hepatologist',
    'Hepatitis D': 'hepatologist',
    'Hepatitis E': 'hepatologist',
    'Alcoholic hepatitis': 'hepatologist',
    'Tuberculosis': 'pulmonologist',
    'Common Cold': 'general_practitioner',
    'Pneumonia': 'pulmonologist',
    'Dimorphic hemmorhoids(piles)': 'proctologist',
    'Heart attack': 'cardiologist',
    'Varicose veins': 'vascular_surgeon',
    'Hypothyroidism': 'endocrinologist',
    'Hyperthyroidism': 'endocrinologist',
    'Hypoglycemia': 'endocrinologist',
    'Osteoarthristis': 'orthopedic',
    'Arthritis': 'rheumatologist',
    '(vertigo) Paroymsal  Positional Vertigo': 'otolaryngologist',
    'Acne': 'dermatologist',
    'Urinary tract infection': 'urologist',
    'Psoriasis': 'dermatologist',
    'Impetigo': 'dermatologist'
};

module.exports = diseaseSpecialtyMap;
